### ISSUE TITLE
bowtie2

### ISSUE THREAD

**Issue by ypriverol** [BioDocker/sandbox#68]
Create a container for bowtie2 (v.2.2.9)(http://bowtie-bio.sourceforge.net/bowtie2/index.shtml)? Bowtie and bowtie2 are really two separate applications; it would be very helpful to have a container for bowtie2.

https://github.com/BioDocker/containers/issues/57

**Comment by ypriverol** [comment]
the sandbox is here already: https://github.com/BioDocker/sandbox/tree/master/bowtie2/2.2.9

**Comment by rmc7777** [comment]
Ah yes I see it now.  I'm new to BioDocker so trying to learn how it works.  How does a container (like bowtie2) migrate from the Sandbox to public Containers?  I can probably test bowtie2 on a cluster.

**Comment by rmc7777** [comment]
I now see bowtie2 in the public repository.  Thanks for doing this.  It's a very popular application.

**Comment by ypriverol** [comment]
Great, If you have any other in my just create an Issue for BioDocker and we will release it. I will close the current issue.
